// Auto-generated friendly labels for all domain tables (audit coverage).
// key = '<app>/<slug>' matching the router route. AR labels are placeholders.
export const MODEL_LABELS: Record<string, { en: string; ar: string }> = {
  "billing/insurance-claim": { en: "Insurance Claim", ar: "Insurance Claim" },
  "billing/invoice": { en: "Invoices", ar: "الفواتير" },
  "billing/invoice-line": { en: "Invoice Line", ar: "Invoice Line" },
  "billing/payment": { en: "Payment", ar: "Payment" },
  "billing/service-price": { en: "Service Price", ar: "Service Price" },
  "clinic/appointment": { en: "Appointments", ar: "المواعيد" },
  "clinic/consultation": { en: "Consultation", ar: "Consultation" },
  "clinic/patient-queue": { en: "Patient Queue", ar: "Patient Queue" },
  "clinic/room": { en: "Room", ar: "Room" },
  "core/address": { en: "Address", ar: "Address" },
  "core/app-user": { en: "App User", ar: "App User" },
  "core/audit-trail": { en: "Audit Trail", ar: "Audit Trail" },
  "core/contact": { en: "Contact", ar: "Contact" },
  "core/event-log": { en: "Event Log", ar: "Event Log" },
  "core/lookup": { en: "Lookup", ar: "Lookup" },
  "core/notification": { en: "Notification", ar: "Notification" },
  "core/party": { en: "Party", ar: "Party" },
  "core/permission": { en: "Permission", ar: "Permission" },
  "core/role": { en: "Role", ar: "Role" },
  "core/role-permission": { en: "Role Permission", ar: "Role Permission" },
  "core/user-role-map": { en: "User Role Map", ar: "User Role Map" },
  "dialysis/session": { en: "Session", ar: "Session" },
  "dialysis/station": { en: "Station", ar: "Station" },
  "emergency/ed-bed": { en: "Ed Bed", ar: "Ed Bed" },
  "emergency/resuscitation": { en: "Resuscitation", ar: "Resuscitation" },
  "emergency/triage": { en: "Triage", ar: "Triage" },
  "emr/allergy": { en: "Allergy", ar: "Allergy" },
  "emr/clinical-note": { en: "Clinical Note", ar: "Clinical Note" },
  "emr/diagnosis": { en: "Diagnosis", ar: "Diagnosis" },
  "emr/encounter": { en: "Encounter", ar: "Encounter" },
  "emr/family-history": { en: "Family History", ar: "Family History" },
  "emr/immunization": { en: "Immunization", ar: "Immunization" },
  "emr/medication-order": { en: "Medication Order", ar: "Medication Order" },
  "emr/patient": { en: "Patients", ar: "المرضى" },
  "emr/social-history": { en: "Social History", ar: "Social History" },
  "emr/vitals": { en: "Vitals", ar: "Vitals" },
  "erp/gl-account": { en: "Gl Account", ar: "Gl Account" },
  "erp/goods-receipt": { en: "Goods Receipts", ar: "إيصالات الاستلام" },
  "erp/goods-receipt-line": { en: "Goods Receipt Line", ar: "Goods Receipt Line" },
  "erp/inventory-item": { en: "Inventory Item", ar: "Inventory Item" },
  "erp/inventory-stock": { en: "Inventory Stock", ar: "Inventory Stock" },
  "erp/purchase-order": { en: "Purchase Order", ar: "Purchase Order" },
  "erp/purchase-order-line": { en: "Purchase Order Line", ar: "Purchase Order Line" },
  "erp/stock-movement": { en: "Stock Movement", ar: "Stock Movement" },
  "erp/supplier": { en: "Supplier", ar: "Supplier" },
  "hr/attendance": { en: "Attendance", ar: "Attendance" },
  "hr/department": { en: "Departments", ar: "الأقسام" },
  "hr/employee": { en: "Employee", ar: "Employee" },
  "hr/employee-department": { en: "Employee Department", ar: "Employee Department" },
  "hr/leave-request": { en: "Leave Request", ar: "Leave Request" },
  "hr/payroll-item": { en: "Payroll Item", ar: "Payroll Item" },
  "hr/payroll-period": { en: "Payroll Period", ar: "Payroll Period" },
  "hr/shift": { en: "Shift", ar: "Shift" },
  "icu/admission": { en: "ICU Admissions", ar: "إدخالات العناية" },
  "icu/bed": { en: "Bed", ar: "Bed" },
  "icu/bed-stay": { en: "Bed Stay", ar: "Bed Stay" },
  "icu/score": { en: "Score", ar: "Score" },
  "icu/support-session": { en: "Support Session", ar: "Support Session" },
  "icu/vitals-stream": { en: "Vitals Stream", ar: "Vitals Stream" },
  "lab/lab-order": { en: "Lab Orders", ar: "طلبات المختبر" },
  "lab/result": { en: "Result", ar: "Result" },
  "lab/sample": { en: "Sample", ar: "Sample" },
  "lab/test-catalog": { en: "Test Catalog", ar: "Test Catalog" },
  "lab/test-panel": { en: "Test Panel", ar: "Test Panel" },
  "lab/test-panel-item": { en: "Test Panel Item", ar: "Test Panel Item" },
  "nursery/cot": { en: "Cot", ar: "Cot" },
  "nursery/growth-entry": { en: "Growth Entry", ar: "Growth Entry" },
  "nursery/neonate-record": { en: "Neonate Record", ar: "Neonate Record" },
  "physio/session": { en: "Session", ar: "Session" },
  "physio/therapy-catalog": { en: "Therapy Catalog", ar: "Therapy Catalog" },
  "physio/treatment-plan": { en: "Treatment Plan", ar: "Treatment Plan" },
  "rad/exam-catalog": { en: "Radiology Exams", ar: "فحوص الأشعة" },
  "rad/image-instance": { en: "Image Instance", ar: "Image Instance" },
  "rad/modality-suite": { en: "Modality Suite", ar: "Modality Suite" },
  "rad/study-request": { en: "Study Request", ar: "Study Request" },
  "rx/administration": { en: "Administration", ar: "Administration" },
  "rx/dispensation": { en: "Dispensation", ar: "Dispensation" },
  "rx/drug-alternative": { en: "Drug Alternative", ar: "Drug Alternative" },
  "rx/drug-interaction": { en: "Drug Interaction", ar: "Drug Interaction" },
  "rx/drug-item": { en: "Drug Items", ar: "الأدوية" },
  "rx/drug-lot": { en: "Drug Lot", ar: "Drug Lot" },
  "rx/stock-movement": { en: "Stock Movement", ar: "Stock Movement" },
  "surgical/intra-op-vitals": { en: "Intra Op Vitals", ar: "Intra Op Vitals" },
  "surgical/operating-room": { en: "Operating Room", ar: "Operating Room" },
  "surgical/post-op-note": { en: "Post Op Note", ar: "Post Op Note" },
  "surgical/pre-op-checklist": { en: "Pre Op Checklist", ar: "Pre Op Checklist" },
  "surgical/procedure-catalog": { en: "Procedure Catalog", ar: "Procedure Catalog" },
  "surgical/surgery": { en: "Surgeries", ar: "العمليات الجراحية" },
  "surgical/surgical-team": { en: "Surgical Team", ar: "Surgical Team" },
};
