-- ============================================================================
-- DEPRECATED — do not apply.
-- ============================================================================
-- This raw-SQL Reports-layer seed has been superseded by the Django ORM write
-- path: apps/core/management/commands/seed_reports_demo.py, invoked from
-- scripts/rebuild_test_db.sh and scripts/setup_db.sh (step 4, after the schema
-- + main seed). Routing the demo data through the models keeps it from drifting
-- from the real schema (GENERATED columns, FKs, validators) the way direct
-- INSERTs could.
--
-- The data previously seeded here (payroll.read RBAC, a July-2026 payroll
-- period + employees + items, and insurance_claims across statuses) is now
-- produced by `python manage.py seed_reports_demo`, which is idempotent.
--
-- This file is kept only as a historical reference; it is no longer in either
-- build script's apply list.
-- ============================================================================
